#!/bin/bash

./compileall ccernn
./compileall demo
./compileall liteon
./compileall ports
./compileall test

./compile demo/axDemo.cpp -exe
./compile ccernn/fx_grains.cpp -exe
./compile ccernn/fx_tempodelay.cpp -exe
./compile test/test_gain_gui.cpp -exe
./compile test/test_gain_gui_skin.cpp -exe

