#!/bin/bash
# ==============================================================================
# linux - axonlib - compileall - bash
# ==============================================================================

echo ""
echo "axonlib 'compileall' script for linux"
echo "-------------------------------------------------------------------------"
echo "syntax: "
echo " ./compileall [path (no '/' at end)] [compile flags (see ./compile)]"

if [ -d "$1/" ];
then
  echo ""
else
  echo ""
  echo "## ERR: path not found - '$1/'"
  exit
fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for _f in ${1}/*
do
  ./compile "$_f" $2 $3 $4 $5 $6 $7 $8 $9 $10
done
IFS=$SAVEIFS

echo ""
echo "** all done!"
