#!/bin/bash

#--------------------------------------------------

# ./compile ccernn/again

#--------------------------------------------------

./compile ccernn/ana_daubechies0
./compile ccernn/ana_fft
./compile ccernn/ana_sigview0
./compile ccernn/ana_vu0

./compile ccernn/fx_blur0
./compile ccernn/fx_cutter0
./compile ccernn/fx_dist0
./compile ccernn/fx_dynamics0
./compile ccernn/fx_envelope0
./compile ccernn/fx_fracdelay0
./compile ccernn/fx_freeze0
./compile ccernn/fx_grains0
./compile ccernn/fx_moddelay0
./compile ccernn/fx_sampler0
./compile ccernn/fx_split0
./compile ccernn/fx_svf0
./compile ccernn/fx_tempodelay0
./compile ccernn/fx_waveshaper0
./compile ccernn/fx_wgtavg0

./compile ccernn/midi_ccaudio0
./compile ccernn/midi_cellular0
./compile ccernn/midi_fibonacci0
./compile ccernn/midi_notelen0
./compile ccernn/midi_syncdelay0
./compile ccernn/midi_transpose0

./compile ccernn/syn_binaural0
./compile ccernn/syn_perc0
./compile ccernn/syn_poly0
./compile ccernn/syn_plucked0

#--------------------------------------------------

./compile liteon/liteon_biquad
./compile liteon/liteon_cpuidtest
./compile liteon/liteon_lofi
./compile liteon/liteon_noise
./compile liteon/liteon_onepole
./compile liteon/liteon_os
./compile liteon/liteon_tilteq

#--------------------------------------------------

./compile ports/autotalent
./compile ports/freeverb
./compile ports/mda_ambience



