#!/bin/bash

function cross_compile_for_linux
{
	echo "--------------------------------------------------"
	echo - $1.so
	echo "--------------------------------------------------" 
	`g++-linux -m32 -D linux -L/_tgz/usr/X11R6/lib -I../ax -I../../vstsdk24 -shared -O3 -Os -fdata-sections -ffunction-sections $1.cpp -s -o $1.so -lpthread -lX11 -Wl,-gc-sections`
	`strip --strip-all $1.so`
	mv $1.so  ../bin
}

function compile_for_windows
{
	echo "--------------------------------------------------"	
	echo - $1.dll	
	echo "--------------------------------------------------"
	`g++ -mwindows -mno-cygwin -I../ax -I../../vstsdk24 -lpthread -shared -O3 -Os -fdata-sections -ffunction-sections $1.cpp -s -o $1.dll -Wl,-gc-sections`
	`strip --strip-all $1.dll`
	mv $1.dll  ../bin
}

# cross_compile_for_linux $1
compile_for_windows $1
