#!/bin/bash

echo
echo deprecated!
echo use compile_vst or compile_exe
echo

## 
## function compile_linux
## {
##   echo - $1.so
##   `g++ -I../ax -I../../vstsdk24 -pedantic -fpermissive -W -Wall -lX11 -lpthread -shared -O3 -Os -msse -mfpmath=sse,387 -fdata-sections ## -ffunction-sections $1.cpp -s -o $1.so -Wl,-gc-sections`
##   `strip --strip-all $1.so`
## 
## }
## 
## function compile_win32
## {
##   echo - $1.dll
##   `i586-mingw32msvc-g++ -I../ax -I../../vstsdk24 -pedantic -fpermissive -W -Wall -mwindows -shared -O3 -Os -msse -mfpmath=sse,387 -## fdata-sections -ffunction-sections $1.cpp -s -o $1.dll -Wl,-gc-sections`
  ## `i586-mingw32msvc-strip --strip-all $1.dll`
## }
## 
## compile_linux $1
## compile_win32 $1
## 
## mv $1.dll ../bin
## mv $1.so  ../bin
## 
## # echo name of script is $0
## # echo first argument is $1
## # echo second argument is $2
## # echo seventeenth argument is $17
## # echo number of arguments is $#

