#!/bin/bash

# brute force!
# would be much better with a "for all .cpp files in directory, do compile..."
# ...later...

#--------------------------------------------------

./compile test/test_gain_nogui.cpp $1 $2
./compile test/test_gain_gui.cpp $1 $2
./compile test/test_gain_gui_skin.cpp $1 $2

./compile demo/axDemo.cpp $1 $2

#--------------------------------------------------

./compile ccernn/fx_distortion.cpp $1 $2
./compile ccernn/fx_tempodelay.cpp $1 $2
./compile ccernn/midi_transpose.cpp $1 $2

