
char* dispatch_enums[] =
{
  //aeffect.h
  (char*)"effOpen",
  (char*)"effClose",
  (char*)"effSetProgram",
  (char*)"effGetProgram",
  (char*)"effSetProgramName",
  (char*)"effGetProgramName",
  (char*)"effGetParamLabel",
  (char*)"effGetParamDisplay",
  (char*)"effGetParamName",
  (char*)"effGetVu (deprecated)",
  (char*)"effSetSampleRate",
  (char*)"effSetBlockSize",
  (char*)"effMainsChanged",
  (char*)"effEditGetRect",
  (char*)"effEditOpen",
  (char*)"effEditClose",
  (char*)"effEditDraw (deprecated)",
  (char*)"effEditMouse (deprecated)",
  (char*)"effEditKey (deprecated)",
  (char*)"effEditIdle",
  (char*)"effEditTop (deprecated)",
  (char*)"effEditSleep (deprecated)",
  (char*)"effIdentify (deprecated)",
  (char*)"effGetChunk",
  (char*)"effSetChunk",
  //aeffectx.h
  (char*)"effProcessEvents",
  (char*)"effCanBeAutomated",
  (char*)"effString2Parameter",
  (char*)"effGetNumProgramCategories (deprecated)",
  (char*)"effGetProgramNameIndexed",
  (char*)"effCopyProgram (deprecated)",
  (char*)"effConnectInput (deprecated)",
  (char*)"effConnectOutput (deprecated)",
  (char*)"effGetInputProperties",
  (char*)"effGetOutputProperties",
  (char*)"effGetPlugCategory",
  (char*)"effGetCurrentPosition (deprecated)",
  (char*)"effGetDestinationBuffer (deprecated)",
  (char*)"effOfflineNotify",
  (char*)"effOfflinePrepare",
  (char*)"effOfflineRun",
  (char*)"effProcessVarIo",
  (char*)"effSetSpeakerArrangement",
  (char*)"effSetBlockSizeAndSampleRate (deprecated)",
  (char*)"effSetBypass",
  (char*)"effGetEffectName",
  (char*)"effGetErrorText (deprecated)",
  (char*)"effGetVendorString",
  (char*)"effGetProductString",
  (char*)"effGetVendorVersion",
  (char*)"effVendorSpecific",
  (char*)"effCanDo",
  (char*)"effGetTailSize",
  (char*)"effIdle (deprecated)",
  (char*)"effGetIcon (deprecated)",
  (char*)"effSetViewPosition (deprecated)",
  (char*)"effGetParameterProperties",
  (char*)"effKeysRequired (deprecated)",
  (char*)"effGetVstVersion",
//#if VST_2_1_EXTENSIONS
  (char*)"effEditKeyDown",
  (char*)"effEditKeyUp",
  (char*)"effSetEditKnobMode",
  (char*)"effGetMidiProgramName",
  (char*)"effGetCurrentMidiProgram",
  (char*)"effGetMidiProgramCategory",
  (char*)"effHasMidiProgramsChanged",
  (char*)"effGetMidiKeyName",
  (char*)"effBeginSetProgram",
  (char*)"effEndSetProgram",
//#endif
//#if VST_2_3_EXTENSIONS
  (char*)"effGetSpeakerArrangement",
  (char*)"effShellGetNextPlugin",
  (char*)"effStartProcess",
  (char*)"effStopProcess",
  (char*)"effSetTotalSampleToProcess",
  (char*)"effSetPanLaw",
  (char*)"effBeginLoadBank",
  (char*)"effBeginLoadProgram",
//#endif
//#if VST_2_4_EXTENSIONS
  (char*)"effSetProcessPrecision",
  (char*)"effGetNumMidiInputChannels",
  (char*)"effGetNumMidiOutputChannels"
//#endif

};
